services:

  appointment-service:
    build: ./application-service
    container_name: appointment-service
    ports:
      - "30001:3001"
    environment:
      - PORT=3001

  patient-service:
    build: ./patient-service
    container_name: patient-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
